config/routes.rb
Placaruva::Application.routes.draw do
  resources :runs, :only => [:index]

  resources :problems, :except => [:edit, :update]

  resources :users, :except => [:edit, :update]

end

app/models/problem.rb
class Problem < ActiveRecord::Base

  has_many :runs

  default_scope order('number')

end

app/models/run.rb
class Run < ActiveRecord::Base

  belongs_to :user
  belongs_to :problem

end

app/models/user.rb
require 'nokogiri'
require 'open-uri'

class User < ActiveRecord::Base

  has_many :runs

  def self.generate(params)
    user = self.new(params)
    uri = 'http://uhunt.felix-halim.net/api/uname2uid/' + user.uva_login
    doc = Nokogiri::HTML(open(uri))
    user.uva_id = doc.content
    user
  end

  def scoreboard
    accepts = Run.where(:user_id => self.id, :verdict => 1).group(:problem_id).select("*,MIN(runs.current_time) AS current_time")
    errors = []
    sumtime = 0
    accepts.each do |problem|
      sumtime = sumtime + problem.current_time
      x = Run.joins(:problem).where("problems.id = ? AND runs.user_id = ? AND runs.current_time < ? AND runs.verdict = ?",problem.problem_id,self.id,problem.current_time,0).group(:problem_id).select("*, COUNT(verdict) AS verdict")
      errors << x[0]
      unless x[0].nil?
        sumtime = sumtime + 20*(x[0].verdict)
      end
    end
    return [accepts.length,sumtime,accepts,errors,self]
  end

  def self.complete_scoreboard
    v = []
    User.all.each do |user|
      v << user.scoreboard
    end
    v.sort_by { |points| [-points[0], points[1]] }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_action :set_problem, only: [:show, :edit, :update, :destroy]

  # GET /problems
  # GET /problems.json
  def index
    @problems = Problem.all
  end

  # GET /problems/1
  # GET /problems/1.json
  def show
  end

  # GET /problems/new
  def new
    @problem = Problem.new
  end

  # GET /problems/1/edit
  def edit
  end

  # POST /problems
  # POST /problems.json
  def create
    @problem = Problem.new(problem_params)

    respond_to do |format|
      if @problem.save
        format.html { redirect_to new_problem_path, notice: 'Problem was successfully created.' }
        format.json { render action: 'show', status: :created, location: @problem }
      else
        format.html { render action: 'new' }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /problems/1
  # PATCH/PUT /problems/1.json
  def update
    respond_to do |format|
      if @problem.update(problem_params)
        format.html { redirect_to @problem, notice: 'Problem was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /problems/1
  # DELETE /problems/1.json
  def destroy
    @problem.destroy
    respond_to do |format|
      format.html { redirect_to problems_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_problem
      @problem = Problem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def problem_params
      params.require(:problem).permit(:number)
    end
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  before_action :set_run, only: [:show, :edit, :update, :destroy]

  # GET /runs
  # GET /runs.json
  def index
    @score = User.complete_scoreboard
    @problems = Problem.all
  end

  # GET /runs/1
  # GET /runs/1.json
  def show
  end

  # GET /runs/new
  def new
    @run = Run.new
  end

  # GET /runs/1/edit
  def edit
  end

  # POST /runs
  # POST /runs.json
  def create
    @run = Run.new(run_params)

    respond_to do |format|
      if @run.save
        format.html { redirect_to @run, notice: 'Run was successfully created.' }
        format.json { render action: 'show', status: :created, location: @run }
      else
        format.html { render action: 'new' }
        format.json { render json: @run.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /runs/1
  # PATCH/PUT /runs/1.json
  def update
    respond_to do |format|
      if @run.update(run_params)
        format.html { redirect_to @run, notice: 'Run was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @run.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /runs/1
  # DELETE /runs/1.json
  def destroy
    @run.destroy
    respond_to do |format|
      format.html { redirect_to runs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_run
      @run = Run.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def run_params
      params.require(:run).permit(:user_uva_id, :problem_number, :verdict, :official_run)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.generate(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to new_user_path, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:uva_login)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/helpers/runs_helper.rb
module RunsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Placaruva" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/runs">Placaruva</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Problems", "/problems"  %></li>
              <li><%= link_to "Users", "/users"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span12">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/problems/_form.html.erb
<%= form_for @problem, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :number, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :number, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                problems_path, :class => 'btn' %>
  </div>
<% end %>

app/views/problems/edit.html.erb
<%- model_class = Problem -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/problems/index.html.erb
<%- model_class = Problem -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:number) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @problems.each do |problem| %>
      <tr>
        <td><%= link_to problem.id, problem_path(problem) %></td>
        <td><%= problem.number %></td>
        <td><%=l problem.created_at %></td>
        <td>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      problem_path(problem),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_problem_path,
            :class => 'btn btn-primary' %>

app/views/problems/new.html.erb
<%- model_class = Problem -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/problems/show.html.erb
<%- model_class = Problem -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:number) %>:</strong></dt>
  <dd><%= @problem.number %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              problems_path, :class => 'btn'  %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              problem_path(@problem),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/runs/_form.html.erb
<%= form_for @run, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :user_uva_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :user_uva_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :problem_number, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :problem_number, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :verdict, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :verdict, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :official_run, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :official_run, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                runs_path, :class => 'btn' %>
  </div>
<% end %>

app/views/runs/edit.html.erb
<%- model_class = Run -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/runs/index.html.erb
<%- model_class = Run -%>
<div class="page-header">
  <h1>Scoreboard</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th> Time </th>
      <%- @problems.each do |problem| %>
      <th><%= problem.number %></th>
      <%- end %>
      <th> Result </th>
    </tr>
  </thead>
  <tbody>
    <% @score.each do |score| %>
    <tr>
      <td><%= score[4].uva_login %></td>
      <%- @problems.each do |problem| %>
      <td>
        <%- vv = score[2].select{|val| val.problem_id == problem.id} %>
        <%- vv2 = score[3].select{|val| val.nil? ? false : val.problem_id == problem.id} %>
        <%- if vv.size > 0 %>
          <%= vv[0].current_time %>(<%= vv2.length > 0 ? vv2[0].verdict : 0 %>)
        <%- else %>
          <%= "-" %>
        <%- end %>
      </td>
      <%- end %>
      <td>
        <%= score[0] %> (<%=score[1] %>)
      </td>
    </tr>
    <%- end %>

  </tbody>
</table>

app/views/runs/new.html.erb
<%- model_class = Run -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/runs/show.html.erb
<%- model_class = Run -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:user_uva_id) %>:</strong></dt>
  <dd><%= @run.user_uva_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:problem_number) %>:</strong></dt>
  <dd><%= @run.problem_number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:verdict) %>:</strong></dt>
  <dd><%= @run.verdict %></dd>
  <dt><strong><%= model_class.human_attribute_name(:official_run) %>:</strong></dt>
  <dd><%= @run.official_run %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              runs_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_run_path(@run), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              run_path(@run),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :uva_login, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :uva_login, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:uva_id) %></th>
      <th><%= model_class.human_attribute_name(:uva_login) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.uva_id %></td>
        <td><%= user.uva_login %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:uva_id) %>:</strong></dt>
  <dd><%= @user.uva_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:uva_login) %>:</strong></dt>
  <dd><%= @user.uva_login %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn'  %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>